name       : pluma-plugins
version    : 1.27.0
release    : 2
source     :
    - https://github.com/mate-desktop/pluma-plugins/releases/download/v1.27.0/pluma-plugins-1.27.0.tar.xz : 28a6fc90273859bc1da8ce830efe873b1612d6dbd225d23c7469606c1b085afe
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set set of plugins for Pluma, the MATE text editor
description: |
    A set set of plugins for Pluma, the MATE text editor. The package pluma-plugins started as a fork of gedit-plugins.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(pluma)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - itstool
rundeps    :
    - pluma
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
