name       : pluma-plugins
version    : 1.26.0
release    : 1
source     :
    - https://github.com/mate-desktop/pluma-plugins/releases/download/v1.26.0/pluma-plugins-1.26.0.tar.xz : d8f38e06ba5360ece1a0a80dd9acab6f9296aeea5b726b76e907b80b64b4f39f
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set set of plugins for Pluma, the MATE text editor
description: |
    A set set of plugins for Pluma, the MATE text editor. The package pluma-plugins started as a fork of gedit-plugins.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(pluma)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - itstool
rundeps    :
    - pluma
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
